language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gperf
  - sudo apt-get install -qq xsltproc
  - sudo apt-get install -qq libexpat-dev
  - autoreconf -vfi

script: ./configure && make clean all check distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
