language: c

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -vfi
  - sudo apt-get install -qq gperf
  - sudo apt-get install -qq xsltproc

script: ./configure && make clean all check distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
