/*** fix-msg-type.h -- fix message types
 *
 * Copyright (C) 2010-2012 Sebastian Freundt
 *
 * Author:  Sebastian Freundt <freundt@ga-group.nl>
 *
 * This file is part of libfixc.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the author nor the names of any contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **/
#if !defined INCLUDED_fix_msg_type_h_
#define INCLUDED_fix_msg_type_h_

/* the enum values chosen, correspond to the ASCII representation */
typedef enum {
	FIXC_MSGTYP_UNK = 0x0000,
	FIXC_MSGTYP_HEARTBEAT = 0x3000/*"0"*/,
	FIXC_MSGTYP_TEST_REQUEST = 0x3100/*"1"*/,
	FIXC_MSGTYP_RESEND_REQUEST = 0x3200/*"2"*/,
	FIXC_MSGTYP_REJECT = 0x3300/*"3"*/,
	FIXC_MSGTYP_SEQUENCE_RESET = 0x3400/*"4"*/,
	FIXC_MSGTYP_LOGOUT = 0x3500/*"5"*/,
	FIXC_MSGTYP_IOI = 0x3600 /*"6"*/,
	FIXC_MSGTYP_ADVERTISEMENT = 0x3700/*"7"*/,
	FIXC_MSGTYP_EXECUTION_REPORT = 0x3800/*"8"*/,
	FIXC_MSGTYP_ORDER_CANCEL_REJECT = 0x3900/*"9"*/,
	FIXC_MSGTYP_LOGON = 0x4100/*"A"*/,
	FIXC_MSGTYP_DERIVATIVE_SECURITY_LIST = 0x4141/*"AA"*/,
	FIXC_MSGTYP_NEW_ORDER_MULTILEG = 0x4142/*"AB"*/,
	FIXC_MSGTYP_MULTILEG_ORDER_CANCEL_REPLACE = 0x4143/*"AC"*/,
	FIXC_MSGTYP_TRADE_CAPTURE_REPORT_REQUEST = 0x4144/*"AD"*/,
	FIXC_MSGTYP_TRADE_CAPTURE_REPORT = 0x4145/*"AE"*/,
	FIXC_MSGTYP_ORDER_MASS_STATUS_REQUEST = 0x4146/*"AF"*/,
	FIXC_MSGTYP_QUOTE_REQUEST_REJECT = 0x4147/*"AG"*/,
	FIXC_MSGTYP_RFQ_REQUEST = 0x4148/*"AH"*/,
	FIXC_MSGTYP_QUOTE_STATUS_REPORT = 0x4149/*"AI"*/,
	FIXC_MSGTYP_QUOTE_RESPONSE = 0x414a/*"AJ"*/,
	FIXC_MSGTYP_CONFIRMATION = 0x414b/*"AK"*/,
	FIXC_MSGTYP_POSITION_MAINTENANCE_REQUEST = 0x414c/*"AL"*/,
	FIXC_MSGTYP_POSITION_MAINTENANCE_REPORT = 0x414d/*"AM"*/,
	FIXC_MSGTYP_REQUEST_FOR_POSITIONS = 0x414e/*"AN"*/,
	FIXC_MSGTYP_REQUEST_FOR_POSITIONS_ACK = 0x414f/*"AO"*/,
	FIXC_MSGTYP_POSITION_REPORT = 0x4150/*"AP"*/,
	FIXC_MSGTYP_TRADE_CAPTURE_REPORT_REQUEST_ACK = 0x4151/*"AQ"*/,
	FIXC_MSGTYP_TRADE_CAPTURE_REPORT_ACK = 0x4152/*"AR"*/,
	FIXC_MSGTYP_ALLOCATION_REPORT = 0x4153/*"AS"*/,
	FIXC_MSGTYP_ALLOCATION_REPORT_Ack = 0x4154/*"AT"*/,
	FIXC_MSGTYP_CONFIRMATION_ACK = 0x4155/*"AU"*/,
	FIXC_MSGTYP_SETTLEMENT_INSTRUCTION_REQUEST = 0x4156/*"AV"*/,
	FIXC_MSGTYP_ASSIGNMENT_REPORT = 0x4157/*"AW"*/,
	FIXC_MSGTYP_COLLATERAL_REQUEST = 0x4158/*"AX"*/,
	FIXC_MSGTYP_COLLATERAL_ASSIGNMENT = 0x4159/*"AY"*/,
	FIXC_MSGTYP_COLLATERAL_RESPONSE = 0x415a/*"AZ"*/,
	FIXC_MSGTYP_NEWS = 0x4200/*"B"*/,
	FIXC_MSGTYP_COLLATERAL_REPORT = 0x4241/*"BA"*/,
	FIXC_MSGTYP_COLLATERAL_INQUIRY = 0x4242/*"BB"*/,
	FIXC_MSGTYP_NETWORK_COUNTERPARTY_SYSTEM_STATUS_REQUEST = 0x4243/*"BC"*/,
	FIXC_MSGTYP_NETWORK_COUNTERPARTY_SYSTEM_STATUS_RESPONSE = 0x4244/*"BD"*/,
	FIXC_MSGTYP_USER_REQUEST = 0x4245/*"BE"*/,
	FIXC_MSGTYP_USER_RESPONSE = 0x4246/*"BF"*/,
	FIXC_MSGTYP_COLLATERAL_INQUIRY_ACK = 0x4247/*"BG"*/,
	FIXC_MSGTYP_CONFIRMATION_REQUEST = 0x4248/*"BH"*/,
	FIXC_MSGTYP_TRADING_SESSION_LIST_REQUEST = 0x4249/*"BI"*/,
	FIXC_MSGTYP_TRADING_SESSION_LIST = 0x424a/*"BJ"*/,
	FIXC_MSGTYP_SECURITY_LIST_UPDATE_REPORT = 0x424b/*"BK"*/,
	FIXC_MSGTYP_ADJUSTED_POSITION_REPORT = 0x424c/*"BL"*/,
	FIXC_MSGTYP_ALLOCATION_INSTRUCTION_ALERT = 0x424d/*"BM"*/,
	FIXC_MSGTYP_EXECUTION_ACKNOWLEDGEMENT = 0x424e/*"BN"*/,
	FIXC_MSGTYP_CONTRARY_INTENTION_REPORT = 0x424f/*"BO"*/,
	FIXC_MSGTYP_SECURITY_DEFINITION_UPDATE_REPORT = 0x4250/*"BP"*/,
	FIXC_MSGTYP_SETTLEMENT_OBLIGATION_REPORT = 0x4251/*"BQ"*/,
	FIXC_MSGTYP_DERIVATIVE_SECURITY_LIST_UPDATE_REPORT = 0x4252/*"BR"*/,
	FIXC_MSGTYP_TRADING_SESSION_LIST_UPDATE_REPORT = 0x4253/*"BS"*/,
	FIXC_MSGTYP_MARKET_DEFINITION_REQUEST = 0x4254/*"BT"*/,
	FIXC_MSGTYP_MARKET_DEFINITION = 0x4255/*"BU"*/,
	FIXC_MSGTYP_MARKET_DEFINITION_UPDATE_REPORT = 0x4256/*"BV"*/,
	FIXC_MSGTYP_APPLICATION_MESSAGE_REQUEST = 0x4257/*"BW"*/,
	FIXC_MSGTYP_APPLICATION_MESSAGE_REQUEST_ACK = 0x4258/*"BX"*/,
	FIXC_MSGTYP_APPLICATION_MESSAGE_REPORT = 0x4259/*"BY"*/,
	FIXC_MSGTYP_ORDER_MASS_ACTION_REPORT = 0x425a/*"BZ"*/,
	FIXC_MSGTYP_EMAIL = 0x4300/*"C"*/,
	FIXC_MSGTYP_ORDER_MASS_ACTION_REQUEST = 0x4341/*"CA"*/,
	FIXC_MSGTYP_USER_NOTIFICATION = 0x4342/*"CB"*/,
	FIXC_MSGTYP_STREAM_ASSIGNMENT_REQUEST = 0x4343/*"CC"*/,
	FIXC_MSGTYP_STREAM_ASSIGNMENT_REPORT = 0x4344/*"CD"*/,
	FIXC_MSGTYP_STREAM_ASSIGNMENT_REPORT_ACK = 0x4345/*"CE"*/,
	FIXC_MSGTYP_NEW_ORDER_SINGLE = 0x4400/*"D"*/,
	FIXC_MSGTYP_NEW_ORDER_LIST = 0x4500/*"E"*/,
	FIXC_MSGTYP_ORDER_CANCEL_REQUEST = 0x4600/*"F"*/,
	FIXC_MSGTYP_ORDER_CANCEL_REPLACE_REQUEST = 0x4700/*"G"*/,
	FIXC_MSGTYP_ORDER_STATUS_REQUEST = 0x4800/*"H"*/,
	FIXC_MSGTYP_ALLOCATION_INSTRUCTION = 0x4a00/*"J"*/,
	FIXC_MSGTYP_LIST_CANCEL_REQUEST = 0x4b00/*"K"*/,
	FIXC_MSGTYP_LIST_EXECUTE = 0x4c00/*"L"*/,
	FIXC_MSGTYP_LIST_STATUS_REQUEST = 0x4d00/*"M"*/,
	FIXC_MSGTYP_LIST_STATUS = 0x4e00/*"N"*/,
	FIXC_MSGTYP_ALLOCATION_INSTRUCTION_ACK = 0x5000/*"P"*/,
	FIXC_MSGTYP_DONT_KNOW_TRADE = 0x5100/*"Q"*/,
	FIXC_MSGTYP_QUOTE_REQUEST = 0x5200/*"R"*/,
	FIXC_MSGTYP_QUOTE = 0x5300/*"S"*/,
	FIXC_MSGTYP_SETTLEMENT_INSTRUCTIONS = 0x5400/*"T"*/,
	FIXC_MSGTYP_MARKET_DATA_REQUEST = 0x5600/*"V"*/,
	FIXC_MSGTYP_MARKET_DATA_SNAPSHOT_FULL_REFRESH = 0x5700/*"W"*/,
	FIXC_MSGTYP_MARKET_DATA_INCREMENTAL_REFRESH = 0x5800/*"X"*/,
	FIXC_MSGTYP_MARKET_DATA_REQUEST_REJECT = 0x5900/*"Y"*/,
	FIXC_MSGTYP_QUOTE_CANCEL = 0x5a00/*"Z"*/,
	FIXC_MSGTYP_QUOTE_STATUS_REQUEST = 0x6100/*"a"*/,
	FIXC_MSGTYP_MASS_QUOTE_ACKNOWLEDGEMENT = 0x6200/*"b"*/,
	FIXC_MSGTYP_SECURITY_DEFINITION_REQUEST = 0x6300/*"c"*/,
	FIXC_MSGTYP_SECURITY_DEFINITION = 0x6400/*"d"*/,
	FIXC_MSGTYP_SECURITY_STATUS_REQUEST = 0x6500/*"e"*/,
	FIXC_MSGTYP_SECURITY_STATUS = 0x6600/*"f"*/,
	FIXC_MSGTYP_TRADING_SESSION_STATUS_REQUEST = 0x6700/*"g"*/,
	FIXC_MSGTYP_TRADING_SESSION_STATUS = 0x6800/*"h"*/,
	FIXC_MSGTYP_MASS_QUOTE = 0x6900/*"i"*/,
	FIXC_MSGTYP_BUSINESS_MESSAGE_REJECT = 0x6a00/*"j"*/,
	FIXC_MSGTYP_BID_REQUEST = 0x6b00/*"k"*/,
	FIXC_MSGTYP_BID_RESPONSE = 0x6c00/*"l"*/,
	FIXC_MSGTYP_LIST_STRIKE_PRICE = 0x6d00/*"m"*/,
	FIXC_MSGTYP_XML_NON_FIX = 0x6e00/*"n"*/,
	FIXC_MSGTYP_REGISTRATION_INSTRUCTIONS = 0x6f00/*"o"*/,
	FIXC_MSGTYP_REGISTRATION_INSTRUCTIONS_RESPONSE = 0x7000/*"p"*/,
	FIXC_MSGTYP_ORDER_MASS_CANCEL_REQUEST = 0x7100/*"q"*/,
	FIXC_MSGTYP_ORDER_MASS_CANCEL_REPORT = 0x7200/*"r"*/,
	FIXC_MSGTYP_NEW_ORDER_CROSS = 0x7300/*"s"*/,
	FIXC_MSGTYP_CROSS_ORDER_CANCEL_REPLACE_REQUEST = 0x7400/*"t"*/,
	FIXC_MSGTYP_CROSS_ORDER_CANCEL_REQUEST = 0x7500/*"u"*/,
	FIXC_MSGTYP_SECURITY_TYPE_REQUEST = 0x7600/*"v"*/,
	FIXC_MSGTYP_SECURITY_TYPES = 0x7700/*"w"*/,
	FIXC_MSGTYP_SECURITY_LIST_REQUEST = 0x7800/*"x"*/,
	FIXC_MSGTYP_SECURITY_LIST = 0x7900/*"y"*/,
	FIXC_MSGTYP_DERIVATIVE_SECURITY_LIST_REQUEST = 0x7a00/*"z"*/,

/* Oh, and FIXimate says:
 * Note: A "U" as the first character in the MsgType field (i.e. U, U2, etc)
 * indicates that the message format is privately defined between the sender and
 * receiver.
 * Don't think we'll support that. */
	FIXC_MSGTYP_USER = 0x5500/*"U"*/,
	FIXC_MSGTYP_USER0 = 0x5530/*"U0"*/,
	FIXC_MSGTYP_USER1 = 0x5531/*"U1"*/,
	FIXC_MSGTYP_USER2 = 0x5532/*"U2"*/,
	FIXC_MSGTYP_USER3 = 0x5533/*"U3"*/,
} fixc_msg_type_t;

#endif	/* INCLUDED_fix_msg_type_h_ */
