/* hand-crafted reverse msgtyp lookup (fixc_msg_type_t -> fixml msg) */
#include "fix-msg-type.h"

static const char *__mty_fixmlify(fixc_msg_type_t mty)
{
	switch (mty) {
	default:
	case FIXC_MSGTYP_UNK:
	case FIXC_MSGTYP_HEARTBEAT:
	case FIXC_MSGTYP_TEST_REQUEST:
	case FIXC_MSGTYP_RESEND_REQUEST:
	case FIXC_MSGTYP_REJECT:
	case FIXC_MSGTYP_SEQUENCE_RESET:
	case FIXC_MSGTYP_LOGOUT:
	case FIXC_MSGTYP_LOGON:
	case FIXC_MSGTYP_XML_NON_FIX:
		return "";
	case FIXC_MSGTYP_ADJUSTED_POSITION_REPORT:
		return "AdjPosRep";
	case FIXC_MSGTYP_ADVERTISEMENT:
		return "Adv";
	case FIXC_MSGTYP_ALLOCATION_INSTRUCTION:
		return "AllocInstrctn";
	case FIXC_MSGTYP_ALLOCATION_INSTRUCTION_ACK:
		return "AllocInstrctnAck";
	case FIXC_MSGTYP_ALLOCATION_INSTRUCTION_ALERT:
		return "AllocInstrAlert";
	case FIXC_MSGTYP_ALLOCATION_REPORT:
		return "AllocRpt";
	case FIXC_MSGTYP_ALLOCATION_REPORT_ACK:
		return "AllocRptAck";
	case FIXC_MSGTYP_APPLICATION_MESSAGE_REPORT:
		return "ApplMsgRpt";
	case FIXC_MSGTYP_APPLICATION_MESSAGE_REQUEST:
		return "ApplMsgReq";
	case FIXC_MSGTYP_APPLICATION_MESSAGE_REQUEST_ACK:
		return "ApplMsgReqAck";
	case FIXC_MSGTYP_ASSIGNMENT_REPORT:
		return "AsgnRpt";
	case FIXC_MSGTYP_BID_REQUEST:
		return "BidReq";
	case FIXC_MSGTYP_BID_RESPONSE:
		return "BidRsp";
	case FIXC_MSGTYP_BUSINESS_MESSAGE_REJECT:
		return "BizMsgRej";
	case FIXC_MSGTYP_COLLATERAL_ASSIGNMENT:
		return "CollAsgn";
	case FIXC_MSGTYP_COLLATERAL_INQUIRY:
		return "CollInq";
	case FIXC_MSGTYP_COLLATERAL_INQUIRY_ACK:
		return "CollInqAck";
	case FIXC_MSGTYP_COLLATERAL_REPORT:
		return "CollRpt";
	case FIXC_MSGTYP_COLLATERAL_REQUEST:
		return "CollReq";
	case FIXC_MSGTYP_COLLATERAL_RESPONSE:
		return "CollRsp";
	case FIXC_MSGTYP_CONFIRMATION:
		return "Cnfm";
	case FIXC_MSGTYP_CONFIRMATION_ACK:
		return "CnfmAck";
	case FIXC_MSGTYP_CONFIRMATION_REQUEST:
		return "CnfmReq";
	case FIXC_MSGTYP_CONTRARY_INTENTION_REPORT:
		return "ContIntRpt";
	case FIXC_MSGTYP_CROSS_ORDER_CANCEL_REPLACE_REQUEST:
		return "CrssOrdCxlRplcReq";
	case FIXC_MSGTYP_CROSS_ORDER_CANCEL_REQUEST:
		return "CrssOrdCxlReq";
	case FIXC_MSGTYP_DERIVATIVE_SECURITY_LIST:
		return "DerivSecList";
	case FIXC_MSGTYP_DERIVATIVE_SECURITY_LIST_REQUEST:
		return "DerivSecListReq";
	case FIXC_MSGTYP_DERIVATIVE_SECURITY_LIST_UPDATE_REPORT:
		return "DerivSecListUpd";
	case FIXC_MSGTYP_DONT_KNOW_TRADE:
		return "DkTrd";
	case FIXC_MSGTYP_EMAIL:
		return "Email";
	case FIXC_MSGTYP_EXECUTION_ACKNOWLEDGEMENT:
		return "ExecAck";
	case FIXC_MSGTYP_EXECUTION_REPORT:
		return "ExecRpt";
	case FIXC_MSGTYP_IOI:
		return "IOI";
	case FIXC_MSGTYP_LIST_CANCEL_REQUEST:
		return "ListCxlReq";
	case FIXC_MSGTYP_LIST_EXECUTE:
		return "ListExct";
	case FIXC_MSGTYP_LIST_STATUS:
		return "ListStat";
	case FIXC_MSGTYP_LIST_STATUS_REQUEST:
		return "ListStatReq";
	case FIXC_MSGTYP_LIST_STRIKE_PRICE:
		return "ListStrkPx";
	case FIXC_MSGTYP_MARKET_DATA_INCREMENTAL_REFRESH:
		return "MktDataInc";
	case FIXC_MSGTYP_MARKET_DATA_REQUEST:
		return "MktDataReq";
	case FIXC_MSGTYP_MARKET_DATA_REQUEST_REJECT:
		return "MktDataReqRej";
	case FIXC_MSGTYP_MARKET_DATA_SNAPSHOT_FULL_REFRESH:
		return "MktDataFull";
	case FIXC_MSGTYP_MARKET_DEFINITION:
		return "MktDef";
	case FIXC_MSGTYP_MARKET_DEFINITION_REQUEST:
		return "MktDefReq";
	case FIXC_MSGTYP_MARKET_DEFINITION_UPDATE_REPORT:
		return "MktDefUpd";
	case FIXC_MSGTYP_MASS_QUOTE:
		return "MassQuot";
	case FIXC_MSGTYP_MASS_QUOTE_ACKNOWLEDGEMENT:
		return "MassQuotAck";
	case FIXC_MSGTYP_MULTILEG_ORDER_CANCEL_REPLACE:
		return "MlegOrdCxlRplc";
	case FIXC_MSGTYP_NETWORK_COUNTERPARTY_SYSTEM_STATUS_REQUEST:
		return "NtwkSysStatReq";
	case FIXC_MSGTYP_NETWORK_COUNTERPARTY_SYSTEM_STATUS_RESPONSE:
		return "NtwkSysStatRsp";
	case FIXC_MSGTYP_NEW_ORDER_CROSS:
		return "NewOrdCrss";
	case FIXC_MSGTYP_NEW_ORDER_LIST:
		return "NewOrdList";
	case FIXC_MSGTYP_NEW_ORDER_MULTILEG:
		return "NewOrdMleg";
	case FIXC_MSGTYP_NEW_ORDER_SINGLE:
		return "Order";
	case FIXC_MSGTYP_NEWS:
		return "News";
	case FIXC_MSGTYP_ORDER_CANCEL_REJECT:
		return "OrdCxlRej";
	case FIXC_MSGTYP_ORDER_CANCEL_REPLACE_REQUEST:
		return "OrdCxlRplcReq";
	case FIXC_MSGTYP_ORDER_CANCEL_REQUEST:
		return "OrdCxlReq";
	case FIXC_MSGTYP_ORDER_MASS_ACTION_REPORT:
		return "OrdMassActRpt";
	case FIXC_MSGTYP_ORDER_MASS_ACTION_REQUEST:
		return "OrdMassActReq";
	case FIXC_MSGTYP_ORDER_MASS_CANCEL_REPORT:
		return "OrdMassCxlRpt";
	case FIXC_MSGTYP_ORDER_MASS_CANCEL_REQUEST:
		return "OrdMassCxlReq";
	case FIXC_MSGTYP_ORDER_MASS_STATUS_REQUEST:
		return "OrdMassStatReq";
	case FIXC_MSGTYP_ORDER_STATUS_REQUEST:
		return "OrdStatReq";
	case FIXC_MSGTYP_POSITION_MAINTENANCE_REPORT:
		return "PosMntRpt";
	case FIXC_MSGTYP_POSITION_MAINTENANCE_REQUEST:
		return "PosMntReq";
	case FIXC_MSGTYP_POSITION_REPORT:
		return "PosRpt";
	case FIXC_MSGTYP_QUOTE:
		return "Quot";
	case FIXC_MSGTYP_QUOTE_CANCEL:
		return "QuotCxl";
	case FIXC_MSGTYP_QUOTE_REQUEST:
		return "QuotReq";
	case FIXC_MSGTYP_QUOTE_REQUEST_REJECT:
		return "QuotReqRej";
	case FIXC_MSGTYP_QUOTE_RESPONSE:
		return "QuotRsp";
	case FIXC_MSGTYP_QUOTE_STATUS_REPORT:
		return "QuotStatRpt";
	case FIXC_MSGTYP_QUOTE_STATUS_REQUEST:
		return "QuotStatReq";
	case FIXC_MSGTYP_RFQ_REQUEST:
		return "RFQReq";
	case FIXC_MSGTYP_REGISTRATION_INSTRUCTIONS:
		return "RgstInstrctns";
	case FIXC_MSGTYP_REGISTRATION_INSTRUCTIONS_RESPONSE:
		return "RgstInstrctnsRsp";
	case FIXC_MSGTYP_REQUEST_FOR_POSITIONS:
		return "ReqForPoss";
	case FIXC_MSGTYP_REQUEST_FOR_POSITIONS_ACK:
		return "ReqForPossAck";
	case FIXC_MSGTYP_SECURITY_DEFINITION:
		return "SecDef";
	case FIXC_MSGTYP_SECURITY_DEFINITION_REQUEST:
		return "SecDefReq";
	case FIXC_MSGTYP_SECURITY_DEFINITION_UPDATE_REPORT:
		return "SecDefUpd";
	case FIXC_MSGTYP_SECURITY_LIST:
		return "SecList";
	case FIXC_MSGTYP_SECURITY_LIST_REQUEST:
		return "SecListReq";
	case FIXC_MSGTYP_SECURITY_LIST_UPDATE_REPORT:
		return "SecListUpd";
	case FIXC_MSGTYP_SECURITY_STATUS:
		return "SecStat";
	case FIXC_MSGTYP_SECURITY_STATUS_REQUEST:
		return "SecStatReq";
	case FIXC_MSGTYP_SECURITY_TYPE_REQUEST:
		return "SecTypReq";
	case FIXC_MSGTYP_SECURITY_TYPES:
		return "SecTyps";
	case FIXC_MSGTYP_SETTLEMENT_INSTRUCTION_REQUEST:
		return "SettlInstrctnReq";
	case FIXC_MSGTYP_SETTLEMENT_INSTRUCTIONS:
		return "SettlInstrctns";
	case FIXC_MSGTYP_SETTLEMENT_OBLIGATION_REPORT:
		return "SettlObligation";
	case FIXC_MSGTYP_STREAM_ASSIGNMENT_REPORT:
		return "StrmAsgnRpt";
	case FIXC_MSGTYP_STREAM_ASSIGNMENT_REPORT_ACK:
		return "StrmAsgnRptACK";
	case FIXC_MSGTYP_STREAM_ASSIGNMENT_REQUEST:
		return "StrmAsgnReq";
	case FIXC_MSGTYP_TRADE_CAPTURE_REPORT:
		return "TrdCaptRpt";
	case FIXC_MSGTYP_TRADE_CAPTURE_REPORT_ACK:
		return "TrdCaptRptAck";
	case FIXC_MSGTYP_TRADE_CAPTURE_REPORT_REQUEST:
		return "TrdCaptRptReq";
	case FIXC_MSGTYP_TRADE_CAPTURE_REPORT_REQUEST_ACK:
		return "TrdCaptRptReqAck";
	case FIXC_MSGTYP_TRADING_SESSION_LIST:
		return "TradSessList";
	case FIXC_MSGTYP_TRADING_SESSION_LIST_REQUEST:
		return "TradSessListReq";
	case FIXC_MSGTYP_TRADING_SESSION_LIST_UPDATE_REPORT:
		return "TrdgSesListUpd";
	case FIXC_MSGTYP_TRADING_SESSION_STATUS:
		return "TrdgSesStat";
	case FIXC_MSGTYP_TRADING_SESSION_STATUS_REQUEST:
		return "TrdgSesStatReq";
	case FIXC_MSGTYP_USER_NOTIFICATION:
		return "UserNotifctn";
	case FIXC_MSGTYP_USER_REQUEST:
		return "UserReq";
	case FIXC_MSGTYP_USER_RESPONSE:
		return "UserRsp";
	}
}
