BEGIN {
  FS="\t"
}
{
  a[$2] = a[$2] "\t" $1
}
END {
  print("\
/* this file is autogenerated, do not edit */\n\
\n\
static const char *fixc_fixmlify(fixc_attr_t tag)\n\
{\n\
	switch (tag) {\n\
	default:\n\
	case FIXC_ATTR_UNK:\n\
		return \"\";\n\
	case FIXC_ATTR_XMLNS:\n\
		return \"xmlns\";\n\
	case FIXC_ATTR_V:\n\
		return \"v\";\n\
	/* the rest is auto generated */\n\
");
  for (i in a) {
    split(substr(a[i], 2), tmp, "\t");
    for (j in tmp) {
      print("\tcase " tmp[j] ":");
    }
    print("\t\treturn \"" substr(i, 2) "\";");
  }
  print("\
	}\n\
}\n");
}
