BEGIN {
  FS="\t"
  print("\
/* this file is autogenerated, do not edit */\n\
\n\
static const char *__cid_fixmlify(fixc_comp_t tag)\n\
{\n\
	switch (tag) {\n\
	default:\n\
	case FIXC_COMP_UNK:\n\
		return \"\";\n\
	case FIXC_COMP_FIXML:\n\
		return \"FIXML\";\n\
	/* the rest is auto generated */\n\
");
}
{
  print("\
\tcase " $1 ":\n\
\t\treturn \"" $2 "\";");
}
END {
  for (i in a) {
    split(substr(a[i], 2), tmp, "\t");
    for (j in tmp) {
      print("\tcase " tmp[j] ":");
    }
    print("\t\treturn \"" i "\";");
  }
  print("\
	}\n\
}\n");
}
